name: Build and deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  build:
    name: Build ⛏
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: ./www
        run: npm install

      - name: Build project
        working-directory: ./www
        run: npm run build

      - name: Copy .htaccess
        working-directory: ./www
        run: cp .htaccess dist/www/

      - name: Archive production artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploiement
          path: ./www/dist/www

  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with: 
          name: deploiement
          path: ${{ vars.WORK_DIR }}

      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with: 
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_usr }}
          password: ${{ secrets.ftp_password }}
